services:
  donas-webpage:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: ghcr.io/donasbydonation/front-end:local
    networks:
      - develop-environment
    ports:
      - "30300:3000"
    environment:
      - "BACK_END_URL=back-end:8080"

networks:
  develop-environment:
    name: develop-environment
    external: true
