name: CICD for main branch

on:
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/front-end:main

  cd:
    needs: ci
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: 'ap-northeast-2'
      AWS_CODEDEPLOY_APP_NAME: 'donas-codedeploy'
      AWS_CODEDEPLOY_DEPLOY_GROUP_NAME: 'donas-codedeploy'
      AWS_S3_BUCKET_NAME: 'donas-server-bucket'
      AWS_S3_BUCKET_PATH: 'codedeploy'
      TGZ_NAME: 'fe.tgz'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Packaging
        run: |
          tar -cpzvf ./$TGZ_NAME appspec.yml aws/scripts/*.sh
      - name: Upload S3
        run: |
          aws s3 cp \
            --region $AWS_DEFAULT_REGION \
            ./$TGZ_NAME s3://$AWS_S3_BUCKET_NAME/$AWS_S3_BUCKET_PATH/$TGZ_NAME
      - name: Code Deploy
        run: |
          aws deploy create-deployment \
            --application-name $AWS_CODEDEPLOY_APP_NAME \
            --deployment-group-name $AWS_CODEDEPLOY_DEPLOY_GROUP_NAME \
            --file-exists-behavior OVERWRITE \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --s3-location bucket=$AWS_S3_BUCKET_NAME,bundleType=tgz,key=$AWS_S3_BUCKET_PATH/$TGZ_NAME \
            --no-paginate
